#%RAML 1.0
title: American Flights API
version: 1.0

/login:
  post:
    body:
      application/json:     
        example: |
          {"name": "уехЩ","password": "123456"}
    responses:
      200:
        body:
          application/json:
            example: |
              {"message": "login success"}